services:

  postgres:
    image: postgres:15
    container_name: yggdrasound_db_container
    environment:
      POSTGRES_DB: yggdrasound_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yggdrasound_password
    ports:
      - "5432:5432"
    volumes:
      - yggdrasound_data:/var/lib/postgresql/data
      - ./yggdrasound_dump.sql:/docker-entrypoint-initdb.d/init.sql


  backend:
    build: ./backend        
    container_name: yggdrasound_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env      
    environment:
      - DB_HOST=postgres    
    depends_on:
      - postgres           

  frontend:
    build: ./frontend
    container_name: yggdrasound_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  yggdrasound_data:
    name: yggdrasound_shared_volume         